### ISSUE TITLE
Atualizar o README

### ISSUE THREAD

**Issue by karlosdaniel451** [hvmello/AED1#3]
Em 8c1b08327cf868ae06bfdf7cf759228e13cab7e2, o projeto, até então gerenciado pelo Ant, se tornou um projeto Maven. Todavia, o **README.md** ainda não foi atualizado segundo essa nova informação, o que pode causar confusão a quem ler o referido arquivo, inclusive ao tentar usar o projeto.

**Comment by hvmello** [comment]
Feito no Commite Update do README
